### PR TITLE
Properly init arrays of MovieDetailedMDB

### LINKED ISSUE #51: Api get Movie detail return nil for production_companies and production_countries
The code I tried is taken from the wiki:

```
MovieMDB.movie(apikey, movieID: 7984, language: "en"){
      apiReturn, movie in
      if let movie = movie{
        print(movie.title)
        print(movie.revenue)
        print(movie.genres[0].name)
        print(movie.production_companies?[0].name)
      }
    }
```

`production_companies`, `production_countries` appear in `apiReturn`, but 

```
print(movie.production_companies?[0].name)
```

return `nil`

### PR DESCRIPTION
**Pull request by djpearce**
Fixing the issue mentioned in: https://github.com/gkye/TheMovieDatabaseSwiftWrapper/pull/48

> Arrays were never initiated, the values were always nil

With the code changes suggestion mentioned it the comments. 

Closes: https://github.com/gkye/TheMovieDatabaseSwiftWrapper/issues/51

### CODE REVIEW

**Comment by djpearce** [comment]
Hey @gkye I have this and a few other PRs open to help modernize the repo, working on a larger Codable sweep as well, should have that relatively soon. Let me know what you think!

**Comment by djpearce** [comment]
@gkye bump !

**Review by gkye — APPROVED** [review]

**Comment by gkye** [comment]
so sorry for the delay @djpearce, I've given you access to the repo. Please merge as you see fit

**Comment by djpearce** [comment]
@gkye no apology needed at all, thanks for the invite to collab!

**Pull request merged**
