### PR TITLE
Implemented Universal Frameworks

### PR DESCRIPTION
**Pull request by Michelasso**
As we agreed I made the frameworks Universal (not sure about the right terminology). I think it is better if I first explain as I proceeded:

- I made a fork into my iCloud folder (that's where I keep all my important projects). This just to say that I had the older version (modified for tvOS) in another place, that has been ignored.
- I made all relevant modifications in the fork
- I have an app using TMDBSwift as a framework (only for tvOS at the moment).
- Pod install couldn't work because it was missing the tvOS part. So:
- I manually added the TMDBSwift project to my app
- I had to manually add the TMDBSwift.framework in Project/Target/General/Linked Frameworks and Libraries
- Then I added the tvOS target for the previous PR.

Now I have done the following:

-  I had to add a folder "TMDBSwift-iOS" for the obj-C umbrella (?) files and move the info.plist and .h there
- I had to rename the iOS target to TMDBSwift-iOS. Actually I renamed all of them in a consistent fashion (TMDBSwift-iOS, TMDBSwift-macOS, TMDBSwift-tvOS), also adding "Tests" at the end for the test folders.
- For each target in Project/Build settings/packaging I changed the product name to "$(PROJECT)" (which is TMDBSwift)
- All frameworks get automatically renamed as well, as $(PROJECT).framework
- the good news is that manually adding the frameworks to an app, Xcode is smart enough to tell the platform, even if the framework names are the same (otherwise it could get a bit confusing). So I guess that's the right path.

After deleting the DerivedData folder in ~/Library I have run the tests for all platforms and they showed all green. I have also successfully compiled and run my app (after changing all imports to "import TMDBSwift"), and it works just fine.

Still I believe the following should be done:

- Update the version tag
- Update the pod files to include both macOS and tvOS platform (I have no idea about how to do it)
- And most important if you can test the iOS version with an app of yours, because I am not sure if I messed up anything for that platform.
- Then you may consider to update the readme file to include all supported platforms!! 😃

### CODE REVIEW

**Comment by Michelasso** [comment]
I am not sure why it is keeping track of all older commits.. I synched my master with yours. Again, this is the second git I work with, so I am a bit of a noob.

**Comment by gkye** [comment]
Still looking at this. Im not too sure how to consolidate all tests into one which can be built on all targets. (Nothing really deviates with from `iOS`, `MacOS` or `tvOS` tests)

**Comment by Michelasso** [comment]
All right. Thanks. Let me know if you need me testing anything.

**Comment by Michelasso** [comment]
@gkye Hi, I had some time so I unified the tests. The concept is that each platform must have a test target (otherwise Xcode couldn't discriminate between one platform and another when running the tests) but we can use single files. So I made a common folder "**TMDBSwiftTests**", where all Swift files have target membership for all test targets, and I had just to change the reference to the test info.plist file in Project/Build settings.

I tested it for all platforms after deleting the "derived data" folder in Xcode library and they all show green! Any change in any file will obviously apply to all platforms.

**Comment by Michelasso** [comment]
I am not sure how it works from Xcode, the old tests folders were still there. I removed them manually, following the instruction in [here](https://gist.github.com/sabarasaba/3080590). I re-did all tests in all platforms after closing Xcode and deleting the derived data folder and they are all green. It should be fine, now.

**Comment by gkye** [comment]
Looks good. thanks for your help 👍

**Comment by gkye** [comment]
I've invited you as a collaborator, thanks again 😄

**Comment by Michelasso** [comment]
All right, thank you. Although I may not be able to dedicate too much time to it. I have just got a puppy! 😍

Plus work should be start soon...

**Pull request merged**
