### PR TITLE
Fixed loading arrays

### PR DESCRIPTION
**Pull request by rickrvo**
Arrays were never initiated, the values were always nil

### CODE REVIEW

**Review by gkye — CHANGES_REQUESTED** [review]
It would be best to initialize it [here](https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/f090c8edf48676e2d982c4a2409567729272d61a/Sources/Models/MovieDetailedMDB.swift#L38):

```
  open var production_companies: [KeywordsMDB]? = []
```

**Comment by MartinP7r** [comment]
> It would be best to initialize it [here](https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/f090c8edf48676e2d982c4a2409567729272d61a/Sources/Models/MovieDetailedMDB.swift#L38):
> 
> ```
>   open var production_companies: [KeywordsMDB]? = []
> ```

In that case, do you still need them to be optional?  
If not, you could 

```swift
open var production_companies: [KeywordsMDB] = []
```

and by extension getting rid of the optional chaining [here](https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/f090c8edf48676e2d982c4a2409567729272d61a/Sources/Models/MovieDetailedMDB.swift#L58) and so on.

**Comment by gkye** [comment]
Optionally is probably not needed but it’s been a while since I looked at the API specs. I think there was a reason for making most of the properties optional, can’t quite remember now though, sorry

**Comment by MartinP7r** [comment]
You're right, it's definitely safer to keep it that way.

**Pull request closed without merging**
